### ISSUE TITLE
Limit output file to just objects needed

### ISSUE THREAD

**Issue by patmo141** [bblanimation/background-processing#7]
**Problem**
For some reason, we get Exception, Access Violation (or something like that) when using the append_form method when trying not to duplicate the entire file.

**Proposed Solution**
Can we write out a library file on the "sending side" instead of trying to *link from/append from** on the background Blender.  Perhaps there is a different way to send "only the assets we need" to each background task.

**Additional context**
The next project I will be building personally will be HEAVILY leveraging background tasks.  Eg loading 10 to 20 assets of 20 to 40MB each, and sending each one for some processing.  So we don't want to duplicate all 20 assets in the duplicate file.

**Comment by bblanimation** [comment]
Fixed by commit 3a8d94f

**Comment by bblanimation** [comment]
This issue was further addressed by commit db9bd50 which switches from appending data blocks on the worker side to sending data blocks from the client side for huge memory savings in some cases.
