### ISSUE TITLE
temp_path on windows.

### ISSUE THREAD

**Issue by arnoldemu** [bblanimation/background-processing#9]
Hi,

I am using Windows 10 and bricker. I am seeing self.temp_path as c:\tmp\background_processing. However, this path is not always accessible because the root of C:\ may be restricted for some users. 

Please consider using: tempfile.gettempdir() to get a windows compatible temporary path.

Thank you.

**Comment by bblanimation** [comment]
Thank you for reporting this! The background processor already uses `tempfile.gettempdir()` – see the `background-processing` master branch, and latest version of Bricker (v1.6.2).
